---
version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      # - image: docker:17.05.0-ce-git
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/hello-world-rails.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/hello-world-rails.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=hello-world-rails -t hello-world-rails .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/hello-world-rails.tar hello-world-rails
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/hello-world-rails.tar
      #- deploy:
      #    name: Push application Docker image
      #    command: |
      #      docker tag hello-world-rails "jrgriffiniii/hello-world-rails:${CIRCLE_SHA1}"
      #      docker push "jrgriffiniii/hello-world-rails:${CIRCLE_SHA1}"

  test:
    docker:
      - image: jrgriffiniii/hello-world-rails:latest
        environment:
          PORT: 3000
      - image: cimg/base:current-22.04
    steps:
      - run:
          name: Wait for the Rails app.
          command: dockerize -wait tcp://localhost:3000 -timeout 1m

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test
      #- test:
      #    requires:
      #      - build