---
version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/hello-world-rails.tar
      # This is not currently used, however, should it be helpful for optimization later...
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/hello-world-rails.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=hello-world-rails -t hello-world-rails .

  test:
    docker:
      - image: cimg/ruby:3.2-browsers
        environment:
          RAILS_ENV: test
      - image: jrgriffiniii/hello-world-rails:latest
        environment:
          PORT: 3000
    steps:
      - run:
          name: Wait for the Rails app.
          command: dockerize -wait tcp://localhost:3000 -timeout 1m

  zap:
    docker:
      #- image: cimg/ruby:3.2-browsers
      #  environment:
      #    RAILS_ENV: test
      - image: docker:latest
      - image: jrgriffiniii/hello-world-rails:latest
        environment:
          PORT: 3000
    steps:
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      #- run:
      #    name: Wait for the Rails app.
      #    command: dockerize -wait tcp://localhost:3000 -timeout 1m
      - run:
          name: Perform a quick scan using ZAP
          command: docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap.sh -cmd -autorun /zap/wrk/zap.yaml

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test
      - zap:
          requires:
            - test